import ApplicationTests from "./app/app-tests.js";
import RouterTests from "./app/router-tests.js";
import AnchorTests from "./app/components/anchor-tests.js";
import ButtonTests from "./app/components/button-tests.js";
import FormInputTests from "./app/components/input-tests.js";
import RegistrationFormTests from "./app/components/form/registration/registration-form-tests.js";
import NotFoundPageTests from "./app/pages/not-found-page-tests.js";
import LoginFormTests from "./app/components/form/login/login-form-tests.js";
import ConfirmPasswordValidatorTests from "./app/validator/confirm-password-validator-tests.js";
import ContainsDigitValidatorTests from "./app/validator/contains-digit-validator-tests.js";
import ContainsLowerLatinValidatorTests from "./app/validator/contains-lower-latin-validator-tests.js";
import ContainsUpperLatinValidatorTests from "./app/validator/contains-upper-latin-validator-tests.js";
import EmptyInputValidatorTests from "./app/validator/empty-input-validator-tests.js";
import NumericOrLatinInputValidatorTests from "./app/validator/numeric-or-latin-input-validator-tests.js";
import ApiServiceTests from './app/services/api-service-tests.js';
import TitleServiceTests from './app/services/title-service-tests.js';
import LoginPageTests from './app/pages/login-page-tests.js';
import RegistrationPageTests from './app/pages/registration-page-tests.js';
import GlyphiconTests from './app/components/glyphicon-tests.js';
import UserDetailsTests from './app/components/user-details-tests.js';
import BreadcrumbsTests from './app/components/breadcrumbs-tests.js';
import FileComponentTests from './app/components/file-list/file/file-component-tests.js';
import FolderComponentTests from './app/components/file-list/folder/folder-component-tests.js';
import FileListTests from './app/components/file-list/file-list-tests.js';
import FileListExplorer from './app/pages/file-list-explorer-tests.js';
import StateManagerTests from './app/state/state-manager-tests.js';
import GetFolderContentActionTests from './app/actions/get-folder-content-action-tests.js';
import GetListItemsMutator from './app/mutators/list-items-mutator-tests.js';
import ListItemsLoadingErrorMutator from './app/mutators/list-items-loading-error-mutator-tests.js';
import ListItemsLoadingMutator from './app/mutators/list-items-loading-mutator-tests.js';
import EventHandlerStorageTests from './app/event/event-handler-storage-tests.js';
import TokenServiceTests from './app/services/token-service-tests.js';
import GetFolderActionTests from './app/actions/get-folder-action-tests.js';
import RouteChangedActionTests from './app/actions/route-changed-action-tests.js';
import ChangeLocationMutatorTests from './app/mutators/location-mutator-tests.js';
import ChangeLocationParametersMutatorTests from './app/mutators/location-parameters-mutator-tests.js';
import GetFolderMutatorTests from './app/mutators/folder-mutator-tests.js';
import RefreshListActionTests from './app/actions/refresh-list-action-tests.js';
import FolderLoadingMutatorTests from './app/mutators/folder-loading-mutator-tests.js';
import FolderLoadingErrorMutatorTests from './app/mutators/folder-loading-error-mutator-tests.js';
import GetRootFolderActionTests from './app/actions/get-root-folder-action-tests.js';
import RootFolderLoadingErrorMutatorTests from './app/mutators/root-folder-loading-error-mutator-tests.js';
import RootFolderMutatorTests from './app/mutators/root-folder-mutator-tests.js';
import RemoveListItemActionTests from './app/actions/remove-list-item-action-tests.js';
import AddToDeletionInProgressMutatorTests from './app/mutators/add-to-deletion-in-progress-mutator-tests.js';
import DeletionIssueMutatorTests from './app/mutators/deletion-issue-mutator-tests.js';
import RemoveFromDeletionInProgressMutatorTests from './app/mutators/remove-from-deletion-in-progress-mutator-tests.js';
import RenameListItemActionTests from './app/actions/rename-list-item-action-tests.js';
import AddToRenamingInProgressMutatorTests from './app/mutators/add-to-renaming-in-progress-mutator-tests.js';
import RenamingItemMutatorTests from './app/mutators/renaming-items-error-mutator-tests.js';
import RemoveFromRenamingInProgressMutatorTests from './app/mutators/remove-from-renaming-in-progress-mutator-tests.js';
import LogOutActionTests from './app/actions/log-out-action-tests.js';
import CreateFolderActionTests from './app/actions/create-folder-action-tests.js';
import FolderCreatingErrorMutatorTests from './app/mutators/folder-creating-error-mutator-tests.js';
import AddParentFolderToCreatingInProgressMutatorTests from
    './app/mutators/add-parent-folder-to-creating-in-progress-mutator-tests.js';
import RemoveParentFolderFromCreatingInProgressMutatorTests from
    './app/mutators/remove-parent-folder-from-creating-in-progress-mutator-tests.js';
import GetUserActionTests from './app/actions/get-user-action-tests.js';
import SetUserMutatorTests from './app/mutators/set-user-mutator-tests.js';
import UserLoadingErrorTests from './app/mutators/user-loading-error-mutator-tests.js';
import UserLoadingTests from './app/mutators/user-loading-mutator-tests.js';
import UploadFileActionTests from './app/actions/upload-file-action-tests.js';
import AddParentFolderToUploadingListMutatorTests from
    './app/mutators/add-parent-folder-to-uploading-list-mutator-tests.js';
import FileUploadingIssueMutator from './app/mutators/file-uploading-issue-mutator-tests.js';
import RemoveParentFolderFromUploadingListMutator from
    './app/mutators/remove-parent-folder-from-uploading-list-mutator-tests.js';
import AddFileToDownloadingInProgressMutatorTests from './app/mutators/add-file-to-downloading-in-progress-mutator-tests.js';
import RemoveFileFromDownloadingInProgressMutatorTests from './app/mutators/remove-file-from-downloading-in-progress-mutator-tests.js';
import FileDownloadingIssueMutatorTests from './app/mutators/file-downloading-issue-mutator-tests.js';
import GetFileContentActionTests from './app/actions/get-file-content-action-tests.js';
